# Generated by Django 3.2.7 on 2022-04-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommarce', '0002_users_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('product_name', models.CharField(default='', max_length=100)),
                ('product_image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('product_image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('product_image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('product_image4', models.ImageField(blank=True, null=True, upload_to='')),
                ('product_image5', models.ImageField(blank=True, null=True, upload_to='')),
                ('cretedBy', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Rate', models.IntegerField(blank=True, null=True)),
                ('product_categorize', models.CharField(choices=[('labtop', 'labtop'), ('PS', 'PS'), ('PS accessories', 'PS accessories'), ('PC', 'PC'), ('Mobilegaming', 'Mobile gaming'), ('Monitor', 'Monitor'), ('accessories', 'accessories'), ('memory', 'memory'), ('Tower', 'Tower')], default='', max_length=40)),
                ('made_in', models.CharField(blank=True, default='', max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
