# Generated by Django 3.2.7 on 2022-04-09 23:55

from django.db import migrations, models
import ecommarce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommarce', '0003_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
        migrations.AddField(
            model_name='products',
            name='details',
            field=models.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image1',
            field=models.ImageField(blank=True, default='', null=True, upload_to=ecommarce.models.upload_product),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image2',
            field=models.ImageField(blank=True, default='', null=True, upload_to=ecommarce.models.upload_product),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image3',
            field=models.ImageField(blank=True, default='', null=True, upload_to=ecommarce.models.upload_product),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image4',
            field=models.ImageField(blank=True, default='', null=True, upload_to=ecommarce.models.upload_product),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image5',
            field=models.ImageField(blank=True, default='', null=True, upload_to=ecommarce.models.upload_product),
        ),
    ]
