# Generated by Django 3.2.7 on 2022-04-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommarce', '0004_auto_20220410_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='reviews',
            field=models.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='', max_length=330),
        ),
    ]
