# Generated by Django 3.2.7 on 2022-04-10 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommarce', '0004_auto_20220410_0155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='details',
            new_name='detail',
        ),
    ]
