# Generated by Django 3.2.7 on 2022-04-13 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommarce', '0005_rename_details_products_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='detail',
            new_name='details',
        ),
    ]
