# Generated by Django 3.2.7 on 2022-04-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommarce', '0006_rename_detail_products_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='', max_length=220),
        ),
    ]
