# Generated by Django 3.2.7 on 2022-04-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommarce', '0008_alter_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(blank=True, default='', max_length=220, null=True),
        ),
    ]
