# Generated by Django 3.2.7 on 2022-04-14 21:54

from django.db import migrations, models
import ecommarce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommarce', '0009_alter_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='img',
            field=models.ImageField(blank=True, default='/seef.jpg', null=True, upload_to=ecommarce.models.upload_path),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
    ]
