# Generated by Django 3.2.7 on 2022-04-14 21:55

from django.db import migrations, models
import ecommarce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommarce', '0010_auto_20220414_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='img',
            field=models.ImageField(blank=True, default='', null=True, upload_to=ecommarce.models.upload_path),
        ),
    ]
