# Generated by Django 3.2.7 on 2022-04-16 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommarce', '0011_alter_users_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
